### ISSUE TITLE
vagrant ssh fails

### ISSUE THREAD

**Issue by josephwinston** [rancherio/os-vagrant#2]
With an up to date versions of vagrant and virtual box on Windows, ssh doesn't work on account for rancher with passwords rancher or vagrant.

$ vagrant version
Installed Version: 1.7.2
Latest Version: 1.7.2

You're running an up-to-date version of Vagrant!
$ VBoxManage.exe --version
4.3.22r98236

$  vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Clearing any previously set forwarded ports...
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
==> default: Forwarding ports...
    default: 22 => 2222 (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: rancher
    default: SSH auth method: private key
    default: Warning: Connection timeout. Retrying...
Text will be echoed in the clear. Please install the HighLine or Termios libraries to suppress echoed text.
rancher@127.0.0.1's password:rancher
rancher@127.0.0.1's password:vagrant
rancher@127.0.0.1's password:
    default: Warning: Authentication failure. Retrying...

**Comment by cloudnautique** [comment]
We disable username/password logins in favor of the keys. I haven't done much with Vagrant on Windows, it looks like there is some work to get keys on Windows going:
https://github.com/Varying-Vagrant-Vagrants/VVV/wiki/Connect-to-Your-Vagrant-Virtual-Machine-with-PuTTY

Doesn't seem like the ideal workflow. Probably makes sense to enable the user login for the Vagrant box.

**Comment by stela5** [comment]
Working for me on Windows 7 with Vagrant 1.7.2 and VirtualBox 4.3.20r96997.  Thanks so much for this excellent OS!

**Comment by josephwinston** [comment]
Given stela5's success, I replaced my old vagrant insecure key with:

https://github.com/mitchellh/vagrant/blob/master/keys/vagrant

Everything works.

Thanks!
