### ISSUE TITLE
Additional NICs don't come UP on boot

### ISSUE THREAD

**Issue by imikushin** [rancherio/os-vagrant#8]
RancherOS v0.1.2 added support for multiple NICs. This doesn't work as expected on Vagrant. 
I've modified `Vagrantfile` to run a few machines to make a virtual network connected to a host-only interface. `config.vm.network :private_network, type: :dhcp` should, in theory, configure the internal network interface (eth1 on host-only VirtualBox network). In practice it crashes vagrant:
```
==> node-01: Configuring and enabling network interfaces...
Vagrant attempted to execute the capability 'configure_networks'
on the detect guest OS 'linux', but the guest doesn't
support that capability. This capability is required for your
configuration of Vagrant. Please either reconfigure Vagrant to
avoid this capability or fix the issue by creating the capability.
```
So, I added `, auto_config: false` to it. Now, the machines do get created, but eth1 is not UP:
```
[rancher@rancher ~]$ ip link
1: lo: <LOOPBACK> mtu 65536 qdisc noop 
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast qlen 1000
    link/ether 08:00:27:fc:5f:eb brd ff:ff:ff:ff:ff:ff
3: eth1: <BROADCAST,MULTICAST> mtu 1500 qdisc noop qlen 1000
    link/ether 08:00:27:2e:a8:48 brd ff:ff:ff:ff:ff:ff
4: docker0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue 
    link/ether 56:84:7a:fe:97:99 brd ff:ff:ff:ff:ff:ff
``` 

Here's the relevant `Vagrantfile` snippet:
```ruby
  (1..($num_minions + 1)).each do |i|
    hostname = "node-%02d" % i

    config.vm.define vmName = hostname do |kHost|
      # kHost.vm.hostname = vmName

      # (skip) configuring memory and vbox specific stuff

      ## FIXME: Configure network not supported by the guest OS???
      kHost.vm.network :private_network, type: :dhcp, auto_config: false
    end
  end
```

**Comment by swissmanu** [comment]
any news here? trying to do the same at the moment, having the same problems.

**Comment by imikushin** [comment]
The issue here is locally cached rancheros vagrant box.

Try `vagrant destroy` and then `vagrant box remove rancheros`. After that, pull this repo and try `vagrant up` again. That should help.

**Comment by cloudnautique** [comment]
@swissmanu, currently @imikushin suggestion is the way to get the machine up. All interfaces presented to the OS are setup for DHCP by default.
We are looking at how to get Vagrant to handle the situation better.

**Comment by imikushin** [comment]
Versioned boxes should help.

**Comment by cloudnautique** [comment]
@imikushin / @swissmanu the new version of the box supports configuring interfaces via the Vagrantfile now. :private_networks now support assigning IPs and DHCP automatically. If you refresh and use this Vagrantfile and the vagrant-rancheros-guest-plugin.rb combo.

**Comment by imikushin** [comment]
Yay!

**Comment by swissmanu** [comment]
@cloudnautique awesome, thx! :)

**Comment by imikushin** [comment]
This is no longer the case, so, closing.
